-- CoupleSync Supabase setup bundle.
-- Generated by npm run sql:supabase.
-- Source files are combined from supabase/migrations in filename order.

-- ============================================================
-- 20260621023000_initial_schema.sql
-- ============================================================
-- CoupleSync initial Supabase schema.
-- Run this once in Supabase SQL Editor or through the Supabase CLI.

create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.couples (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Our Calendar',
  invite_code text not null unique default lower(encode(gen_random_bytes(5), 'hex')),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.couple_members (
  couple_id uuid not null references public.couples(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text check (role in ('him', 'her')),
  joined_at timestamptz not null default now(),
  primary key (couple_id, user_id)
);

create unique index couple_members_one_role_per_couple
  on public.couple_members(couple_id, role)
  where role is not null;

create table public.layers (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  slug text,
  name text not null,
  type text not null check (type in ('schedule', 'habits', 'todos', 'custom')),
  owner_role text check (owner_role in ('him', 'her', 'both')),
  color text,
  sort_order integer not null default 0,
  is_system boolean not null default false,
  is_visible_by_default boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index layers_unique_slug_per_couple
  on public.layers(couple_id, slug)
  where slug is not null;

create table public.events (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  layer_id uuid references public.layers(id) on delete set null,
  title text not null,
  event_date date not null,
  start_time time,
  end_time time,
  all_day boolean not null default false,
  owner_role text not null default 'both' check (owner_role in ('him', 'her', 'both')),
  source text not null default 'manual' check (source in ('manual', 'google', 'apple')),
  external_id text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index events_couple_date_idx on public.events(couple_id, event_date);

create table public.habit_definitions (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  name text not null,
  color text not null default '#4ade80',
  owner_role text not null default 'both' check (owner_role in ('him', 'her', 'both')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.habit_logs (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  habit_id uuid not null references public.habit_definitions(id) on delete cascade,
  habit_date date not null,
  owner_role text not null default 'both' check (owner_role in ('him', 'her', 'both')),
  logged_by uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create index habit_logs_couple_date_idx on public.habit_logs(couple_id, habit_date);

create unique index habit_logs_one_per_role_date
  on public.habit_logs(couple_id, habit_id, habit_date, owner_role);

create table public.todos (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  text text not null,
  completed boolean not null default false,
  scheduled_date date,
  assignee_role text not null default 'both' check (assignee_role in ('him', 'her', 'both', 'unassigned')),
  source_message_id uuid,
  created_by uuid references auth.users(id) on delete set null,
  completed_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index todos_couple_scheduled_date_idx on public.todos(couple_id, scheduled_date);

create table public.inbox_messages (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  parent_id uuid references public.inbox_messages(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete set null,
  sender_role text not null default 'him' check (sender_role in ('him', 'her')),
  category text not null default 'idea' check (category in ('idea', 'plan', 'love')),
  content text not null,
  converted_event_id uuid references public.events(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index inbox_messages_couple_parent_idx on public.inbox_messages(couple_id, parent_id);

alter table public.todos
  add constraint todos_source_message_fk
  foreign key (source_message_id)
  references public.inbox_messages(id)
  on delete set null;

create table public.calendar_connections (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('google', 'apple')),
  provider_account_id text,
  scopes text[] not null default '{}',
  token_reference text,
  sync_cursor text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider, provider_account_id)
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch_updated_at
  before update on public.profiles
  for each row execute function public.touch_updated_at();

create trigger couples_touch_updated_at
  before update on public.couples
  for each row execute function public.touch_updated_at();

create trigger layers_touch_updated_at
  before update on public.layers
  for each row execute function public.touch_updated_at();

create trigger events_touch_updated_at
  before update on public.events
  for each row execute function public.touch_updated_at();

create trigger habit_definitions_touch_updated_at
  before update on public.habit_definitions
  for each row execute function public.touch_updated_at();

create trigger todos_touch_updated_at
  before update on public.todos
  for each row execute function public.touch_updated_at();

create trigger inbox_messages_touch_updated_at
  before update on public.inbox_messages
  for each row execute function public.touch_updated_at();

create trigger calendar_connections_touch_updated_at
  before update on public.calendar_connections
  for each row execute function public.touch_updated_at();

create or replace function public.is_couple_member(target_couple_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and exists (
      select 1
      from public.couple_members
      where couple_id = target_couple_id
        and user_id = auth.uid()
    );
$$;

create or replace function public.seed_couple_defaults()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.layers (couple_id, slug, name, type, owner_role, color, sort_order, is_system)
  values
    (new.id, 'him_schedule', 'His Schedule', 'schedule', 'him', '#d1e6e0', 10, true),
    (new.id, 'her_schedule', 'Her Schedule', 'schedule', 'her', '#f0e6eb', 20, true),
    (new.id, 'shared_habits', 'Shared Habits', 'habits', 'both', '#e0e5ed', 30, true),
    (new.id, 'todos', 'To-Dos', 'todos', 'both', '#d8dadc', 40, true);

  insert into public.habit_definitions (couple_id, name, color, owner_role, sort_order)
  values
    (new.id, 'Vocabulary', '#4ade80', 'both', 10),
    (new.id, 'Shower', '#d8dadc', 'both', 20),
    (new.id, 'Exercise', '#a65d5d', 'both', 30);

  return new;
end;
$$;

create trigger couples_seed_defaults
  after insert on public.couples
  for each row execute function public.seed_couple_defaults();

create or replace function public.create_couple_workspace(
  p_name text default 'Our Calendar',
  p_role text default null
)
returns table (couple_id uuid, invite_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_couple public.couples%rowtype;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if p_role is not null and p_role not in ('him', 'her') then
    raise exception 'invalid_role';
  end if;

  insert into public.couples (name, created_by)
  values (coalesce(nullif(trim(p_name), ''), 'Our Calendar'), auth.uid())
  returning * into new_couple;

  insert into public.couple_members (couple_id, user_id, role)
  values (new_couple.id, auth.uid(), p_role);

  return query
    select new_couple.id, new_couple.invite_code;
end;
$$;

create or replace function public.join_couple_by_invite_code(
  p_invite_code text,
  p_role text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target_couple_id uuid;
  normalized_code text;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if p_role is not null and p_role not in ('him', 'her') then
    raise exception 'invalid_role';
  end if;

  normalized_code := lower(trim(p_invite_code));

  select id
  into target_couple_id
  from public.couples
  where invite_code = normalized_code;

  if target_couple_id is null then
    raise exception 'invite_code_not_found';
  end if;

  insert into public.couple_members (couple_id, user_id, role)
  values (target_couple_id, auth.uid(), p_role)
  on conflict (couple_id, user_id)
  do update set role = coalesce(excluded.role, public.couple_members.role);

  return target_couple_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.couples enable row level security;
alter table public.couple_members enable row level security;
alter table public.layers enable row level security;
alter table public.events enable row level security;
alter table public.habit_definitions enable row level security;
alter table public.habit_logs enable row level security;
alter table public.todos enable row level security;
alter table public.inbox_messages enable row level security;
alter table public.calendar_connections enable row level security;

create policy "profiles are visible to self and couple members"
  on public.profiles
  for select
  to authenticated
  using (
    id = auth.uid()
    or exists (
      select 1
      from public.couple_members mine
      join public.couple_members theirs
        on theirs.couple_id = mine.couple_id
      where mine.user_id = auth.uid()
        and theirs.user_id = public.profiles.id
    )
  );

create policy "users can insert their own profile"
  on public.profiles
  for insert
  to authenticated
  with check (id = auth.uid());

create policy "users can update their own profile"
  on public.profiles
  for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

create policy "members can view their couples"
  on public.couples
  for select
  to authenticated
  using (public.is_couple_member(id));

create policy "users can create their own couple"
  on public.couples
  for insert
  to authenticated
  with check (created_by = auth.uid());

create policy "members can update their couples"
  on public.couples
  for update
  to authenticated
  using (public.is_couple_member(id))
  with check (public.is_couple_member(id));

create policy "members can view couple membership"
  on public.couple_members
  for select
  to authenticated
  using (user_id = auth.uid() or public.is_couple_member(couple_id));

create policy "creators and members can add themselves"
  on public.couple_members
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and (
      public.is_couple_member(couple_id)
      or exists (
        select 1
        from public.couples
        where id = couple_id
          and created_by = auth.uid()
      )
    )
  );

create policy "members can update membership"
  on public.couple_members
  for update
  to authenticated
  using (public.is_couple_member(couple_id))
  with check (public.is_couple_member(couple_id));

create policy "members can view layers"
  on public.layers
  for select
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can create layers"
  on public.layers
  for insert
  to authenticated
  with check (public.is_couple_member(couple_id));

create policy "members can update layers"
  on public.layers
  for update
  to authenticated
  using (public.is_couple_member(couple_id))
  with check (public.is_couple_member(couple_id));

create policy "members can view events"
  on public.events
  for select
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can create events"
  on public.events
  for insert
  to authenticated
  with check (public.is_couple_member(couple_id));

create policy "members can update events"
  on public.events
  for update
  to authenticated
  using (public.is_couple_member(couple_id))
  with check (public.is_couple_member(couple_id));

create policy "members can view habit definitions"
  on public.habit_definitions
  for select
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can create habit definitions"
  on public.habit_definitions
  for insert
  to authenticated
  with check (public.is_couple_member(couple_id));

create policy "members can update habit definitions"
  on public.habit_definitions
  for update
  to authenticated
  using (public.is_couple_member(couple_id))
  with check (public.is_couple_member(couple_id));

create policy "members can view habit logs"
  on public.habit_logs
  for select
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can create habit logs"
  on public.habit_logs
  for insert
  to authenticated
  with check (public.is_couple_member(couple_id));

create policy "members can update habit logs"
  on public.habit_logs
  for update
  to authenticated
  using (public.is_couple_member(couple_id))
  with check (public.is_couple_member(couple_id));

create policy "members can view todos"
  on public.todos
  for select
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can create todos"
  on public.todos
  for insert
  to authenticated
  with check (public.is_couple_member(couple_id));

create policy "members can update todos"
  on public.todos
  for update
  to authenticated
  using (public.is_couple_member(couple_id))
  with check (public.is_couple_member(couple_id));

create policy "members can view inbox messages"
  on public.inbox_messages
  for select
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can create inbox messages"
  on public.inbox_messages
  for insert
  to authenticated
  with check (public.is_couple_member(couple_id));

create policy "members can update inbox messages"
  on public.inbox_messages
  for update
  to authenticated
  using (public.is_couple_member(couple_id))
  with check (public.is_couple_member(couple_id));

create policy "users can view their calendar connections"
  on public.calendar_connections
  for select
  to authenticated
  using (user_id = auth.uid() and public.is_couple_member(couple_id));

create policy "users can create their calendar connections"
  on public.calendar_connections
  for insert
  to authenticated
  with check (user_id = auth.uid() and public.is_couple_member(couple_id));

create policy "users can update their calendar connections"
  on public.calendar_connections
  for update
  to authenticated
  using (user_id = auth.uid() and public.is_couple_member(couple_id))
  with check (user_id = auth.uid() and public.is_couple_member(couple_id));

grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.couples to authenticated;
grant select, insert, update on public.couple_members to authenticated;
grant select, insert, update on public.layers to authenticated;
grant select, insert, update on public.events to authenticated;
grant select, insert, update on public.habit_definitions to authenticated;
grant select, insert, update on public.habit_logs to authenticated;
grant select, insert, update on public.todos to authenticated;
grant select, insert, update on public.inbox_messages to authenticated;
grant select, insert, update on public.calendar_connections to authenticated;
grant execute on function public.create_couple_workspace(text, text) to authenticated;
grant execute on function public.join_couple_by_invite_code(text, text) to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.profiles;
    exception when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table public.couples;
    exception when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table public.couple_members;
    exception when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table public.layers;
    exception when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table public.events;
    exception when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table public.habit_definitions;
    exception when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table public.habit_logs;
    exception when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table public.todos;
    exception when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table public.inbox_messages;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

-- ============================================================
-- 20260621102000_external_calendar_sync_readiness.sql
-- ============================================================
-- External calendar sync readiness.
-- Run after 20260621023000_initial_schema.sql.

alter table public.calendar_connections
  add column if not exists sync_status text not null default 'idle'
    check (sync_status in ('idle', 'syncing', 'error')),
  add column if not exists last_synced_at timestamptz,
  add column if not exists last_sync_error text;

create unique index if not exists events_unique_external_per_couple_source
  on public.events(couple_id, source, external_id)
  where source in ('google', 'apple')
    and external_id is not null;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.calendar_connections;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

-- ============================================================
-- 20260621113000_google_calendar_oauth_readiness.sql
-- ============================================================
-- Google Calendar OAuth readiness.
-- Run after 20260621102000_external_calendar_sync_readiness.sql.

create unique index if not exists calendar_connections_unique_user_provider
  on public.calendar_connections(couple_id, user_id, provider);

create unique index if not exists events_unique_source_external_for_upsert
  on public.events(couple_id, source, external_id);

-- ============================================================
-- 20260622113000_delete_policy_readiness.sql
-- ============================================================
-- Enable member-owned destructive actions from the app UI.
-- This migration only grants delete permissions and policies; it does not delete existing data.

create policy "members can delete non-system layers"
  on public.layers
  for delete
  to authenticated
  using (public.is_couple_member(couple_id) and is_system = false);

create policy "members can delete events"
  on public.events
  for delete
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can delete habit definitions"
  on public.habit_definitions
  for delete
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can delete habit logs"
  on public.habit_logs
  for delete
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can delete todos"
  on public.todos
  for delete
  to authenticated
  using (public.is_couple_member(couple_id));

create policy "members can delete inbox messages"
  on public.inbox_messages
  for delete
  to authenticated
  using (public.is_couple_member(couple_id));

grant delete on public.layers to authenticated;
grant delete on public.events to authenticated;
grant delete on public.habit_definitions to authenticated;
grant delete on public.habit_logs to authenticated;
grant delete on public.todos to authenticated;
grant delete on public.inbox_messages to authenticated;

-- ============================================================
-- 20260622124500_profile_weather_location.sql
-- ============================================================
-- Profile weather location fields for the right-panel personal status view.
-- Run after the initial schema and delete-policy readiness migrations.

alter table public.profiles
  add column if not exists weather_city text,
  add column if not exists weather_country text,
  add column if not exists weather_latitude double precision,
  add column if not exists weather_longitude double precision,
  add column if not exists weather_updated_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_weather_latitude_range'
  ) then
    alter table public.profiles
      add constraint profiles_weather_latitude_range
      check (weather_latitude is null or (weather_latitude >= -90 and weather_latitude <= 90));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_weather_longitude_range'
  ) then
    alter table public.profiles
      add constraint profiles_weather_longitude_range
      check (weather_longitude is null or (weather_longitude >= -180 and weather_longitude <= 180));
  end if;
end $$;

-- ============================================================
-- 20260623090000_inbox_mood_category.sql
-- ============================================================
-- Allow mood records in Couple Inbox messages.

alter table public.inbox_messages
  drop constraint if exists inbox_messages_category_check;

alter table public.inbox_messages
  add constraint inbox_messages_category_check
  check (category in ('idea', 'plan', 'love', 'mood'));

-- ============================================================
-- 20260623131000_feature_wishes.sql
-- ============================================================
-- Shared feature wishlist for future CoupleSync improvements.

create table if not exists public.feature_wishes (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  content text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists feature_wishes_couple_created_at_idx
  on public.feature_wishes(couple_id, created_at);

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'feature_wishes_touch_updated_at'
  ) then
    create trigger feature_wishes_touch_updated_at
      before update on public.feature_wishes
      for each row execute function public.touch_updated_at();
  end if;
end $$;

alter table public.feature_wishes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'feature_wishes'
      and policyname = 'members can view feature wishes'
  ) then
    create policy "members can view feature wishes"
      on public.feature_wishes
      for select
      to authenticated
      using (public.is_couple_member(couple_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'feature_wishes'
      and policyname = 'members can create feature wishes'
  ) then
    create policy "members can create feature wishes"
      on public.feature_wishes
      for insert
      to authenticated
      with check (public.is_couple_member(couple_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'feature_wishes'
      and policyname = 'members can update feature wishes'
  ) then
    create policy "members can update feature wishes"
      on public.feature_wishes
      for update
      to authenticated
      using (public.is_couple_member(couple_id))
      with check (public.is_couple_member(couple_id));
  end if;
end $$;

grant select, insert, update on public.feature_wishes to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.feature_wishes;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

-- ============================================================
-- 20260707090000_todo_rollovers.sql
-- ============================================================
-- Todo rollover history for moved unfinished tasks.

create table if not exists public.todo_rollovers (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  todo_id uuid not null references public.todos(id) on delete cascade,
  from_date date not null,
  to_date date not null,
  text text not null,
  assignee_role text not null default 'both' check (assignee_role in ('him', 'her', 'both', 'unassigned')),
  rolled_over_by uuid references auth.users(id) on delete set null,
  rolled_over_at timestamptz not null default now()
);

create unique index if not exists todo_rollovers_unique_todo_from_date
  on public.todo_rollovers(couple_id, todo_id, from_date);

create index if not exists todo_rollovers_couple_from_date_idx
  on public.todo_rollovers(couple_id, from_date);

alter table public.todo_rollovers enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'todo_rollovers'
      and policyname = 'members can view todo rollovers'
  ) then
    create policy "members can view todo rollovers"
      on public.todo_rollovers
      for select
      to authenticated
      using (public.is_couple_member(couple_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'todo_rollovers'
      and policyname = 'members can create todo rollovers'
  ) then
    create policy "members can create todo rollovers"
      on public.todo_rollovers
      for insert
      to authenticated
      with check (public.is_couple_member(couple_id));
  end if;
end $$;

grant select, insert on public.todo_rollovers to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.todo_rollovers;
    exception when duplicate_object then null;
    end;
  end if;
end $$;
